                Segment Code Para Public 'Code' Use16

                EXTRN   Introduction    : NEAR
                EXTRN   PrepareForDemo  : NEAR
                EXTRN   FlipPages       : NEAR
                EXTRN   DrawObject      : NEAR
                EXTRN   EraseObject     : NEAR
                EXTRN   MirrorObject    : NEAR
                EXTRN   UpdateWriter    : NEAR

                Ends

                Segment Data Para Public 'Data' Use16

                EXTRN   DrawPage        : WORD
                EXTRN   YTable          : WORD

                Ends
