                EXTRN   Product         : BYTE
                EXTRN   Vivian          : BYTE
                EXTRN   Program         : BYTE
                EXTRN   ATron           : BYTE
                EXTRN   Graphics        : BYTE
                EXTRN   Shadow          : BYTE
                EXTRN   Music           : BYTE
                EXTRN   For             : BYTE
                EXTRN   Penta           : BYTE
                EXTRN   Gram            : BYTE

ProductHeight   EQU     95
ProductWidth    EQU     208
ProductXCoord   EQU     56
ProductYCoord   EQU     105

VivianHeight    EQU     25
VivianWidth     EQU     84
VivianXCoord    EQU     0
VivianYCoord    EQU     80

ProgramHeight   EQU     34
ProgramWidth    EQU     240
ProgramXCoord   EQU     80
ProgramYCoord   EQU     200

ATronHeight     EQU     25
ATronWidth      EQU     188
ATronXCoord     EQU     0
ATronYCoord     EQU     80

GraphicsHeight  EQU     34
GraphicsWidth   EQU     172
GraphicsXCoord  EQU     148
GraphicsYCoord  EQU     200

ShadowHeight    EQU     25
ShadowWidth     EQU     204
ShadowXCoord    EQU     0
ShadowYCoord    EQU     80

MusicHeight     EQU     34
MusicWidth      EQU     108
MusicXCoord     EQU     212
MusicYCoord     EQU     200

ForHeight       EQU     25
ForWidth        EQU     52
ForXCoord       EQU     132
ForYCoord       EQU     180

PentaHeight     EQU     97
PentaWidth      EQU     320
PentaXCoord     EQU     0
PentaYCoord     EQU     0

GramHeight      EQU     97
GramWidth       EQU     320
GramXCoord      EQU     0
GramYCoord      EQU     298
