                Segment Data Para Public 'Data' Use16

Struc           Object
  NumFaces      DW      0
  NumVerts      DW      0
  VertTable     DW      0
  FaceTable     DW      0
                Ends

                EXTRN   CurrObject      : WORD
                EXTRN   ScreenCoords    : WORD
                EXTRN   FaceIndices     : WORD
                EXTRN   FaceCoordList   : WORD

                Ends
